name: Check Even Minute

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  check-time:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Run Python to check if the current minute is even
      - name: Check if the current minute is even
        run: |
          python -c "
import datetime
minute = datetime.datetime.now().minute
if minute % 2 == 0:
    print('Current minute is even')
else:
    print('Current minute is odd')
          "
