name: Check Even Minute

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  check-minute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check if the current minute is even
        run: |
          python script.py

      - name: Check if the current second is between 31 and 59
        run: |
          python pythontest2.py
           
    
