name: Check Even Minute

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  check-time:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install Python if necessary
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Run Python script to check if the current minute is even
      - name: Check if the current minute is even
        run: |
          python -c "
import datetime
minute = datetime.datetime.now().minute
if minute % 2 == 0:
    print(f'The current minute ({minute}) is even.')
else:
    print(f'The current minute ({minute}) is odd.')
          "
